// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDebugRecord = "debug_record"

// DebugRecord mapped from table <debug_record>
type DebugRecord struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:变量id" json:"id"`                        // 变量id
	PlanID       int32     `gorm:"column:plan_id;not null;comment:计划id" json:"plan_id"`                                   // 计划id
	Status       bool      `gorm:"column:status;not null;comment:调试结果" json:"status"`                                     // 调试结果
	ResultInfo   string    `gorm:"column:result_info;not null;comment:Case调试详情" json:"result_info"`                       // Case调试详情
	CreateUserID int32     `gorm:"column:create_user_id;not null;comment:创建人id" json:"create_user_id"`                    // 创建人id
	CreateTime   time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	IsDelete     bool      `gorm:"column:is_delete;not null;comment:是否删除" json:"is_delete"`                               // 是否删除
}

// TableName DebugRecord's table name
func (*DebugRecord) TableName() string {
	return TableNameDebugRecord
}
