// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOperationLog = "operation_log"

// OperationLog mapped from table <operation_log>
type OperationLog struct {
	ID            int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                            // ID
	SourceName    string    `gorm:"column:source_name;not null;comment:调用方系统或模块的名字" json:"source_name"`                      // 调用方系统或模块的名字
	SourceID      int32     `gorm:"column:source_id;not null;comment:操作的对象ID" json:"source_id"`                              // 操作的对象ID
	OperationType int32     `gorm:"column:operation_type;not null;comment:操作别名" json:"operation_type"`                       // 操作别名
	OperatorID    int32     `gorm:"column:operator_id;not null;comment:操作人" json:"operator_id"`                              // 操作人
	ValueBefore   string    `gorm:"column:value_before;not null;comment:变更前" json:"value_before"`                            // 变更前
	ValueAfter    string    `gorm:"column:value_after;not null;comment:变更后" json:"value_after"`                              // 变更后
	ValueDiff     string    `gorm:"column:value_diff;not null;comment:差异变更" json:"value_diff"`                               // 差异变更
	CreatedTime   time.Time `gorm:"column:created_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_time"` // 创建时间
	UpdatedTime   time.Time `gorm:"column:updated_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_time"` // 更新时间
}

// TableName OperationLog's table name
func (*OperationLog) TableName() string {
	return TableNameOperationLog
}
