// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameParameterFile = "parameter_files"

// ParameterFile mapped from table <parameter_files>
type ParameterFile struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	PlanID       int32     `gorm:"column:plan_id;not null;comment:测试计划ID" json:"plan_id"`                                   // 测试计划ID
	FileName     string    `gorm:"column:file_name;not null;comment:文件名" json:"file_name"`                                  // 文件名
	Size         int32     `gorm:"column:size;not null;comment:文件大小" json:"size"`                                           // 文件大小
	Rows         int32     `gorm:"column:rows;not null;comment:文件行数" json:"rows"`                                           // 文件行数
	Column       string    `gorm:"column:column;not null;comment:文件列信息" json:"column"`                                      // 文件列信息
	Status       bool      `gorm:"column:status;not null;default:1;comment:是否启用" json:"status"`                             // 是否启用
	CreateUserID int32     `gorm:"column:create_user_id;not null;comment:创建人id" json:"create_user_id"`                      // 创建人id
	CreateTime   time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"`   // 创建时间
	UpdateUserID int32     `gorm:"column:update_user_id;comment:最后修改人id" json:"update_user_id"`                             // 最后修改人id
	UpdateTime   time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:最后修改时间" json:"update_time"` // 最后修改时间
	IsDelete     bool      `gorm:"column:is_delete;not null;comment:是否删除" json:"is_delete"`                                 // 是否删除
}

// TableName ParameterFile's table name
func (*ParameterFile) TableName() string {
	return TableNameParameterFile
}
