// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameScene = "scene"

// Scene mapped from table <scene>
type Scene struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:场景id" json:"id"`                          // 场景id
	PlanID       int32     `gorm:"column:plan_id;not null;comment:场景id" json:"plan_id"`                                     // 场景id
	Sort         int32     `gorm:"column:sort;not null;default:1;comment:排序" json:"sort"`                                   // 排序
	SceneType    int32     `gorm:"column:scene_type;not null;comment:场景类型" json:"scene_type"`                               // 场景类型
	SceneName    string    `gorm:"column:scene_name;not null;comment:场景名" json:"scene_name"`                                // 场景名
	ExportInfo   string    `gorm:"column:export_info;not null;comment:导出数据信息" json:"export_info"`                           // 导出数据信息
	Disabled     bool      `gorm:"column:disabled;not null;comment:是否禁用" json:"disabled"`                                   // 是否禁用
	CreateUserID int32     `gorm:"column:create_user_id;not null;comment:创建人id" json:"create_user_id"`                      // 创建人id
	UpdateUserID int32     `gorm:"column:update_user_id;not null;comment:最后修改人id" json:"update_user_id"`                    // 最后修改人id
	CreateTime   time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"`   // 创建时间
	UpdateTime   time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:最后修改时间" json:"update_time"` // 最后修改时间
	IsDelete     bool      `gorm:"column:is_delete;not null;comment:是否删除" json:"is_delete"`                                 // 是否删除
}

// TableName Scene's table name
func (*Scene) TableName() string {
	return TableNameScene
}
