// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSceneVariable = "scene_variable"

// SceneVariable mapped from table <scene_variable>
type SceneVariable struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:变量id" json:"id"`                        // 变量id
	SceneID      int32     `gorm:"column:scene_id;not null;comment:所属场景id" json:"scene_id"`                               // 所属场景id
	VariableName string    `gorm:"column:variable_name;not null;comment:变量名" json:"variable_name"`                        // 变量名
	VariableVal  string    `gorm:"column:variable_val;not null;comment:变量值" json:"variable_val"`                          // 变量值
	Remark       string    `gorm:"column:remark;comment:描述" json:"remark"`                                                // 描述
	CreateUserID int32     `gorm:"column:create_user_id;not null;comment:创建人id" json:"create_user_id"`                    // 创建人id
	UpdateUserID int32     `gorm:"column:update_user_id;not null;comment:修改人id" json:"update_user_id"`                    // 修改人id
	CreateTime   time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime   time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:修改时间" json:"update_time"` // 修改时间
	IsDelete     bool      `gorm:"column:is_delete;not null;comment:是否删除" json:"is_delete"`                               // 是否删除
}

// TableName SceneVariable's table name
func (*SceneVariable) TableName() string {
	return TableNameSceneVariable
}
