// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTag = "tag"

// Tag mapped from table <tag>
type Tag struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Label      string    `gorm:"column:label;not null;comment:标签名" json:"label"`                                        // 标签名
	Type       int32     `gorm:"column:type;not null;comment:标签类型" json:"type"`                                         // 标签类型
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	IsDelete   bool      `gorm:"column:is_delete;not null;comment:是否删除" json:"is_delete"`                               // 是否删除
}

// TableName Tag's table name
func (*Tag) TableName() string {
	return TableNameTag
}
