// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTaskInfo = "task_info"

// TaskInfo mapped from table <task_info>
type TaskInfo struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Type         int32     `gorm:"column:type;not null;comment:脚本类型" json:"type"`                                         // 脚本类型
	Cron         string    `gorm:"column:cron;not null;comment:执行cron表达式" json:"cron"`                                    // 执行cron表达式
	TaskInfo     string    `gorm:"column:task_info;not null;comment:脚本信息" json:"task_info"`                               // 脚本信息
	Enable       bool      `gorm:"column:enable;not null;comment:是否启用" json:"enable"`                                     // 是否启用
	CreateUserID int32     `gorm:"column:create_user_id;not null;comment:创建人id" json:"create_user_id"`                    // 创建人id
	UpdateUserID int32     `gorm:"column:update_user_id;not null;comment:更新人id" json:"update_user_id"`                    // 更新人id
	CreateTime   time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime   time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
	IsDelete     bool      `gorm:"column:is_delete;not null;comment:是否删除" json:"is_delete"`                               // 是否删除
}

// TableName TaskInfo's table name
func (*TaskInfo) TableName() string {
	return TableNameTaskInfo
}
