// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameReport = "report"

// Report mapped from table <report>
type Report struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:测试报告id" json:"id"`                        // 测试报告id
	ReportName   string    `gorm:"column:report_name;not null;comment:测试报告名" json:"report_name"`                            // 测试报告名
	PlanID       int32     `gorm:"column:plan_id;not null;comment:测试计划id" json:"plan_id"`                                   // 测试计划id
	Status       bool      `gorm:"column:status;not null;default:1;comment:测试报告状态" json:"status"`                           // 测试报告状态
	Duration     int32     `gorm:"column:duration;not null;comment:预计持续时间" json:"duration"`                                 // 预计持续时间
	PressType    int32     `gorm:"column:press_type;not null;comment:压测模式" json:"press_type"`                               // 压测模式
	EngineList   string    `gorm:"column:engine_list;not null;comment:施压机ip列表" json:"engine_list"`                          // 施压机ip列表
	Concurrency  int32     `gorm:"column:concurrency;not null;comment:起始并发数" json:"concurrency"`                            // 起始并发数
	PressResult  string    `gorm:"column:press_result;comment:压测聚合结果" json:"press_result"`                                  // 压测聚合结果
	CreateUserID int32     `gorm:"column:create_user_id;not null;comment:创建人id" json:"create_user_id"`                      // 创建人id
	UpdateUserID int32     `gorm:"column:update_user_id;not null;comment:最后修改人id" json:"update_user_id"`                    // 最后修改人id
	CreateTime   time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"`   // 创建时间
	UpdateTime   time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:最后修改时间" json:"update_time"` // 最后修改时间
	EndTime      time.Time `gorm:"column:end_time;comment:结束时间" json:"end_time"`                                            // 结束时间
	Vum          int32     `gorm:"column:vum;comment:Vum" json:"vum"`                                                       // Vum
	IsDelete     bool      `gorm:"column:is_delete;not null;comment:是否删除" json:"is_delete"`                                 // 是否删除
	Rps          int32     `gorm:"column:rps;comment:rps" json:"rps"`                                                       // rps
}

// TableName Report's table name
func (*Report) TableName() string {
	return TableNameReport
}
