// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePlan = "plan"

// Plan mapped from table <plan>
type Plan struct {
	ID             int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:测试计划id" json:"id"`                        // 测试计划id
	PlanName       string    `gorm:"column:plan_name;not null;comment:测试计划名称" json:"plan_name"`                               // 测试计划名称
	EngineCount    int32     `gorm:"column:engine_count;not null;default:1;comment:压测机数量" json:"engine_count"`                // 压测机数量
	PressInfo      string    `gorm:"column:press_info;not null;comment:施压策略" json:"press_info"`                               // 施压策略
	GlobalVariable string    `gorm:"column:global_variable;not null;comment:全局变量" json:"global_variable"`                     // 全局变量
	DefaultHeader  string    `gorm:"column:default_header;not null;comment:默认请求头" json:"default_header"`                      // 默认请求头
	SamplingInfo   string    `gorm:"column:sampling_info;not null;comment:采样策略" json:"sampling_info"`                         // 采样策略
	ServerInfo     string    `gorm:"column:server_info;not null;comment:管理服务" json:"server_info"`                             // 管理服务
	BreakType      int32     `gorm:"column:break_type;not null;comment:熔断机制类型" json:"break_type"`                             // 熔断机制类型
	BreakValue     float32   `gorm:"column:break_value;not null;comment:熔断阈值" json:"break_value"`                             // 熔断阈值
	TaskID         int32     `gorm:"column:task_id;not null;comment:定时任务id" json:"task_id"`                                   // 定时任务id
	Remark         string    `gorm:"column:remark;comment:备注" json:"remark"`                                                  // 备注
	DebugStatus    bool      `gorm:"column:debug_status;not null;comment:是否调试通过" json:"debug_status"`                         // 是否调试通过
	CreateUserID   int32     `gorm:"column:create_user_id;not null;comment:创建人id" json:"create_user_id"`                      // 创建人id
	UpdateUserID   int32     `gorm:"column:update_user_id;not null;comment:最后修改人id" json:"update_user_id"`                    // 最后修改人id
	CreateTime     time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"`   // 创建时间
	UpdateTime     time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:最后修改时间" json:"update_time"` // 最后修改时间
	IsDelete       bool      `gorm:"column:is_delete;not null;comment:是否删除" json:"is_delete"`                                 // 是否删除
}

// TableName Plan's table name
func (*Plan) TableName() string {
	return TableNamePlan
}
